[package]
name = "clocker"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = "3.1.1"
